# docker-compose.yml

name: ipharma

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipharma
      MYSQL_USER: ipharma_user
      MYSQL_PASSWORD: ipharma_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://ipharma_user:ipharma_pass@mysql:3306/ipharma
      SHADOW_DATABASE_URL: mysql://ipharma_user:ipharma_pass@mysql:3306/ipharma_shadow
    ports:
      - "5000:5000"
    command: node dist/server.js

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  mysql-data:
